modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="Lil revive_music"
version="1.1"
displayName="Lil ReZero Tom"
description="Se supone que debe de sonar la cancion de ReZero ATTM: Lil Tomioka"